// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Usa placeholder durante build se DATABASE_URL não estiver disponível
    // O Prisma Client pode ser gerado sem conexão real ao banco
    url: env("DATABASE_URL") || "postgresql://placeholder:placeholder@localhost:5432/placeholder",
  },
});
