// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Carrega dotenv apenas se não estiver em produção (Vercel já fornece as variáveis)
if (process.env.NODE_ENV !== 'production') {
  try {
    require("dotenv").config();
  } catch {
    // dotenv não disponível, assume que variáveis já estão no ambiente
  }
}

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // A URL do datasource está definida no schema.prisma
  // Este arquivo apenas configura migrations e outras opções
});
